version: '3'

services:

  #backend:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.backend
  #    target: base
  #  environment:
  #    PHP_IDE_CONFIG: "serverName=Docker"
  #    XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes"
  #  extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #  volumes:
  #    - ./backend:/var/www/html
  #    - ./telemedizin-bundle:/var/www/telemedizin-bundle
  #  ports:
  #    - "9003:9003"  # Xdebug Port

  mailhog:
    image: mailhog/mailhog:latest
    container_name: telemedizin_mailhog
    ports:
      - "1025:1025"  # SMTP Server
      - "8025:8025"  # Web Interface
    networks:
      - telemedizin_network
    depends_on:
      - backend

networks:
  telemedizin_network:
    driver: bridge 