version: '3'

services:
  # Backend (Laravel 11)
  backend:
    image: php:8.3-fpm
    container_name: telemedizin_backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./test_bundle_telemedizin:/var/www/test_bundle_telemedizin
    depends_on:
      - db
    networks:
      - telemedizin_network
    command: >
      bash -c "apt-get update && apt-get install -y git zip unzip libpq-dev && 
      docker-php-ext-install pdo pdo_mysql && 
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && 
      composer install && 
      php artisan migrate:fresh --seed --force &&
      php artisan serve --host=0.0.0.0 --port=8000"
      
    ports:
      - "8000:8000"

  # Frontend (React with TypeScript)
  frontend:
    image: node:20
    container_name: telemedizin_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      bash -c "npm install && 
      npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - telemedizin_network

  # Database (MySQL)
  db:
    image: mysql:8.0
    container_name: telemedizin_db
    restart: always
    environment:
      MYSQL_DATABASE: telemedizin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: telemedizin
      MYSQL_PASSWORD: telemedizin
    ports:
      - "3306:3306"
    volumes:
      - telemedizin_db_data:/var/lib/mysql
    networks:
      - telemedizin_network

networks:
  telemedizin_network:
    driver: bridge

volumes:
  telemedizin_db_data:
